server:
  port: 8091

  security:
    user:
      name: root
      password: root

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka/

spring:
  application:
    name: APIGatewayJWT2

  security:
    user:
      name: root
      password: root

  datasource:
    url: jdbc:mysql://localhost:3306/capstonedb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: sendadmcap9@gmail.com  # Replace with your actual Gmail address
    password: gtfa fonz lszl yvze          # Replace with your actual Gmail password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "aVeryLongRandomStringThatIsHardToGuess1234567890"
  expiration: 3600000  # 1 hour in milliseconds


