export const LABELS = {
  DOCTOR_DETAILS: 'Doctor Details',
  BOOK_APPOINTMENT: 'Book Appointment',
  SELECT_DATE: 'Select Date:',
  SELECT_TIME_SLOT: 'Select Time Slot:',
  REASON_FOR_VISIT: 'Reason for Visit:',
  CONFIRM_APPOINTMENT: 'Confirm Appointment',
  LOADING: 'Loading...',
  LOADING_DATES: 'Loading available dates...',
  LOADING_SLOTS: 'Loading available time slots...',
  NO_AVAILABLE_SLOTS: 'No available slots for the selected date.',
  INCOMPLETE_INFORMATION: 'Incomplete Information',
  FILL_ALL_FIELDS: 'Please fill out all fields before booking.',
  SPECIALIZATION: 'Specialization:',
  EXPERIENCE: 'Experience:',
  HOSPITAL: 'Hospital:',
  LOCATION: 'Location:',
  DESCRIPTION: 'Description:',
  FULL_NAME: 'Full Name:',
  AGE: 'Age:',
  GENDER: 'Gender:',
  CONTACT_NUMBER: 'Contact Number:',
  EDIT_PROFILE: 'Edit Profile',
  VIEW_PROFILE: 'View Profile',
  SELECT: 'Select',
  FILTER_BY_DATE: 'Filter by Date:',
  DISPLAY_ALL: 'Display All',
  DATE: 'Date:',
  TIME: 'Time:',
  REASON: 'Reason:',
  STATUS: 'Status:',
  CANCEL: 'Cancel',
  NO_APPOINTMENTS: 'No appointments available for the selected date.',
  SEARCH_BY_NAME_OR_SPECIALIZATION: 'Search by name or specialization',
  FILTERS: 'Filters',
  STATE: 'State',
  CITY: 'City',
  SEARCH: 'Search',
  CLEAR_FILTERS: 'Clear Filters',
  NO_DOCTORS_FOUND: 'No doctors found',
  ADDRESS: 'Address:',
  BOOK_APPOINTMENT_BUTTON: 'Book Appointment',
};

export const MESSAGES = {
  CONFIRM_APPOINTMENT: (date, time) => `Are you sure you want to book an appointment on ${date} at ${time}?`,
  BOOKING_APPOINTMENT: 'Please wait while we confirm your appointment.',
  APPOINTMENT_BOOKED: (date, time) => `Your appointment is scheduled for ${date} at ${time}.`,
  BOOKING_FAILED: 'An error occurred while booking the appointment. Please try again later.',
  FETCH_DOCTOR_PROFILE_ERROR: 'Error fetching the doctor profile',
  FETCH_AVAILABLE_DATES_ERROR: 'Failed to fetch available dates. Please try again later.',
  FETCH_AVAILABLE_SLOTS_ERROR: 'Failed to fetch available time slots. Please try again later.',
  FETCH_PATIENT_PROFILE_ERROR: 'Error fetching the patient profile',
  UPDATE_PROFILE_SUCCESS: 'Profile updated successfully!',
  UPDATE_PROFILE_ERROR: 'Error updating the profile. Please try again.',
  FETCH_APPOINTMENTS_ERROR: 'Failed to fetch appointments',
  CANCEL_APPOINTMENT_CONFIRM: 'Do you really want to cancel this appointment?',
  CANCEL_APPOINTMENT_SUCCESS: 'Appointment cancelled successfully!',
  CANCEL_APPOINTMENT_ERROR: 'Failed to cancel the appointment. Please try again.',
  PATIENT_ID_NOT_FOUND: 'Patient ID not found. Please log in again.',
  FETCH_DOCTORS_ERROR: 'There was an error fetching the doctors!',
  FETCH_CITIES_ERROR: 'There was an error fetching the cities!',
  FETCH_HOSPITALS_ERROR: 'There was an error fetching the hospitals!',
  FETCH_FILTERED_DOCTORS_ERROR: 'There was an error fetching the filtered doctors!',
};

export const ROUTES = {
  DOCTOR_PROFILE: (doctorId) => `/doctorProfile/${doctorId}`,
  AVAILABLE_DATES: (doctorId) => `/patient/appointment/available-dates?doctorId=${doctorId}`,
  AVAILABLE_SLOTS: (doctorId, date) => `/patient/appointment/available-slots?doctorId=${doctorId}&date=${date}`,
  BOOK_APPOINTMENT: '/patient/appointment/bookappointment',
  PATIENT_APPOINTMENTS: '/patientappointments',
  PATIENT_HOME: '/patienthome',
  GET_PATIENT_PROFILE: (patientId) => `/patient/getPatientProfile/${patientId}`,
  UPDATE_PROFILE: (patientId) => `/patient/updateProfile/${patientId}`,
  UPCOMING_APPOINTMENTS: (patientId) => `/appointment/upcoming/${patientId}`,
  CANCEL_APPOINTMENT: (appointmentId, patientId) => `/appointment/cancel/${appointmentId}/${patientId}`,
  FETCH_DOCTORS: '/patient/doctors',
  FETCH_DOCTORS_FILTER: '/patient/doctors/filter',
};

export const BUTTON_TEXT = {
  YES_BOOK_IT: 'Yes, book it!',
  CANCEL: 'Cancel',
  OK: 'OK',
  EDIT: 'Edit',
  SAVE: 'Save',
  DISPLAY_ALL: 'Display All',
  YES_CANCEL_IT: 'Yes, cancel it!',
  NO_KEEP_IT: 'No, keep it',
  SEARCH: 'Search',
  CLEAR_FILTERS: 'Clear Filters',
  FILTERS: 'Filters',
};

export const TITLES = {
  CONFIRM_APPOINTMENT: 'Confirm Appointment',
  BOOKING_APPOINTMENT: 'Booking Appointment...',
  APPOINTMENT_BOOKED: 'Appointment Booked!',
  BOOKING_FAILED: 'Booking Failed',
  INCOMPLETE_INFORMATION: 'Incomplete Information',
  EDIT_PROFILE: 'Edit Profile',
  VIEW_PROFILE: 'View Profile',
  ARE_YOU_SURE: 'Are you sure?',
  PLEASE_WAIT: 'Please wait...',
  CANCELLED: 'Cancelled!',
  ERROR: 'Error',
};

export const GENDER_OPTIONS = {
  MALE: 'Male',
  FEMALE: 'Female',
  OTHER: 'Other',
};
